var {
  ATOM_ACCESS_TOKEN,
  ATOM_API_URL,
  ATOM_ARCH,
  ATOM_ELECTRON_URL,
  ATOM_ELECTRON_VERSION,
  ATOM_HOME,
  ATOM_PACKAGES_URL,
  ATOM_REPOS_HOME,
  ATOM_RESOURCE_PATH,
  GITHUB_USER,
  GYP_MSVS_VERSION,
  HOME,
  HTTP_PROXY,
  HTTPS_PROXY,
  LOCALAPPDATA,
  NODE_DEBUG,
  NODE_TLS_REJECT_UNAUTHORIZED,
  npm_config_arch,
  npm_config_cache,
  npm_config_disturl,
  npm_config_node_gyp,
  npm_config_python,
  npm_config_registry,
  npm_config_runtime,
  npm_config_target_arch,
  npm_config_target,
  Path,
  PATH,
  ProgramFiles,
  PYTHON,
  RUSTUP_HOME,
  SystemDrive,
  USERPROFILE,
} = process.env;

const apm_vars = {
  atom_access_token: ATOM_ACCESS_TOKEN,
  atom_api_url: ATOM_API_URL,
  atom_arch: ATOM_ARCH,
  atom_electron_url: ATOM_ELECTRON_URL,
  atom_electron_version: ATOM_ELECTRON_VERSION,
  atom_home: ATOM_HOME,
  atom_packages_url: ATOM_PACKAGES_URL,
  atom_repos_home: ATOM_REPOS_HOME,
  atom_resource_path: ATOM_RESOURCE_PATH,
  github_user: GITHUB_USER,
  gyp_msvs_version: GYP_MSVS_VERSION,
  home: HOME,
  http_proxy: HTTP_PROXY,
  https_proxy: HTTPS_PROXY,
  localappdata: LOCALAPPDATA,
  node_debug: NODE_DEBUG,
  node_tls_reject_unauthorized: NODE_TLS_REJECT_UNAUTHORIZED,
  arch: npm_config_arch,
  cache: npm_config_cache,
  disturl: npm_config_disturl,
  node_gyp: npm_config_node_gyp,
  python: npm_config_python,
  registry: npm_config_registry,
  runtime: npm_config_runtime,
  target_arch: npm_config_target_arch,
  target: npm_config_target,
  path: PATH ?  PATH : Path,
  programfiles: ProgramFiles,
  python: PYTHON,
  rustup_home: RUSTUP_HOME,
  systemdrive: SystemDrive,
  userprofile: USERPROFILE,
};
